name: new_build

on: [push]

jobs:
  build:
    runs-on: windows-2019
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12", "3.13"]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Build & install
      shell: bash
      run: |
        set -x &&
        export DISTUTILS_DEBUG=1 &&
        python -mpip install --upgrade pip &&
        python -mpip install setuptools &&
        python tools/build-windows-wheel.py &&
        choco install --no-progress ghostscript &&
        pip install 'numpy!=1.19.4' &&
        python -mpip install dist/*.whl &&
        python tools/ensure-mpl-test-data.py &&
        # pytest-{instafail,timeout} useful for hanging tests.
        python -mpip install pytest pytest-instafail pytest-timeout
    - name: Test
      shell: bash
      run: |
        set -x &&
        python -mpip list &&
        python -c 'import mplcairo as m, pprint as p; p.pprint(m.get_versions())' &&
        # Skip tests triggering to-be-investigated fatal error on Windows :(
        ./run-mpl-test-suite.py --tolerance=60 --instafail --timeout=300 --capture=no --verbose &&
        PYTHONFAULTHANDLER=1 PYTHONIOENCODING=utf-8 ./run-examples.py
    - uses: actions/upload-artifact@v4
      with:
        name: wheel-win-${{ matrix.python-version }}
        path: dist/*.whl
      if: ${{ always() }}
    - uses: actions/upload-artifact@v4
      with:
        name: result_images-win-py${{ matrix.python-version }}
        path: result_images/
      if: ${{ failure() }}

  merge-wheels:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/upload-artifact/merge@v4
      with:
        name: wheels
        pattern: wheel-*
        delete-merged: true
